# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-check-circle",
                        help_text="Например: bi-wifi, bi-tv, bi-cup-hot",
                        max_length=60,
                        verbose_name="иконка Bootstrap Icons",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("comfort", "Комфорт"),
                            ("tech", "Технологии"),
                            ("food", "Питание"),
                            ("wellness", "Здоровье и красота"),
                            ("service", "Сервис"),
                        ],
                        db_index=True,
                        default="comfort",
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Показывать в карточке номера крупно",
                        verbose_name="выделить на сайте",
                    ),
                ),
            ],
            options={
                "verbose_name": "удобство",
                "verbose_name_plural": "удобства",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="краткое описание"),
                ),
                (
                    "max_guests",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="макс. гостей",
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("single", "Одна кровать"),
                            ("double", "Двуспальная"),
                            ("twin", "Две раздельные"),
                            ("king", "King-size"),
                            ("bunk", "Двухъярусная"),
                        ],
                        default="double",
                        max_length=20,
                        verbose_name="тип кровати",
                    ),
                ),
                (
                    "area_sqm",
                    models.PositiveSmallIntegerField(
                        default=25, verbose_name="площадь (м²)"
                    ),
                ),
                (
                    "base_price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="базовая цена за ночь",
                    ),
                ),
                (
                    "weekend_price_per_night",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Если не указана — используется базовая цена",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="цена за ночь (выходные)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rooms/thumbnails/%Y/%m/",
                        verbose_name="превью",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активна"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="показывать на главной",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categories",
                        to="hotel.amenity",
                        verbose_name="удобства",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория номера",
                "verbose_name_plural": "категории номеров",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="rooms/gallery/%Y/%m/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Для SEO и доступности",
                        max_length=200,
                        verbose_name="alt текст",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="главное фото"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotel.roomcategory",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото номера",
                "verbose_name_plural": "фото номеров",
                "ordering": ["-is_primary", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="RoomReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="общая оценка",
                    ),
                ),
                (
                    "cleanliness_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="чистота",
                    ),
                ),
                (
                    "service_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="сервис",
                    ),
                ),
                (
                    "comfort_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="комфорт",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="заголовок"
                    ),
                ),
                ("body", models.TextField(verbose_name="текст отзыва")),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="одобрен"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="одобрен в"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="одобрил",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hotel.roomcategory",
                        verbose_name="категория",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="гость",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Новогодние праздники 2025",
                        max_length=100,
                        verbose_name="название периода",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="начало периода"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="конец периода"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="цена за ночь",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Минимальный срок бронирования в этот период",
                        verbose_name="минимум ночей",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_prices",
                        to="hotel.roomcategory",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "сезонная цена",
                "verbose_name_plural": "сезонные цены",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="номер комнаты"
                    ),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(default=1, verbose_name="этаж"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Свободен"),
                            ("occupied", "Занят"),
                            ("maintenance", "На обслуживании"),
                            ("cleaning", "Уборка"),
                            ("blocked", "Заблокирован"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="балкон"),
                ),
                (
                    "has_sea_view",
                    models.BooleanField(default=False, verbose_name="вид на море"),
                ),
                (
                    "has_mountain_view",
                    models.BooleanField(default=False, verbose_name="вид на горы"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="внутренние заметки"),
                ),
                (
                    "last_cleaned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последняя уборка"
                    ),
                ),
                (
                    "extra_amenities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Удобства конкретного номера сверх категории",
                        related_name="rooms",
                        to="hotel.amenity",
                        verbose_name="доп. удобства",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="hotel.roomcategory",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "номер",
                "verbose_name_plural": "номера",
                "ordering": ["floor", "number"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"],
                        name="hotel_room_status_d62efc_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="roomreview",
            constraint=models.UniqueConstraint(
                fields=("guest", "booking"), name="unique_review_per_booking"
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonalprice",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="seasonal_price_end_after_start",
            ),
        ),
    ]
