# Generated by Django 5.0.4 on 2026-05-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_patronymic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passport_issued_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_issued_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_series",
        ),
    ]
