# Generated by Django 5.0.4 on 2026-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_passport_issued_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("receptionist", "Ресепшн"),
                    ("manager", "Менеджер"),
                    ("admin", "Администратор"),
                    ("super_admin", "Супер-администратор"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="роль",
            ),
        ),
    ]
