# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="вопрос")),
                ("answer", models.TextField(verbose_name="ответ")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "Бронирование"),
                            ("checkin", "Заезд и выезд"),
                            ("services", "Услуги"),
                            ("payment", "Оплата"),
                            ("general", "Общее"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["category", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HotelGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/hotel/%Y/%m/", verbose_name="изображение"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="заголовок"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Для SEO и доступности",
                        max_length=200,
                        verbose_name="alt текст",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("exterior", "Экстерьер"),
                            ("lobby", "Лобби"),
                            ("restaurant", "Ресторан"),
                            ("spa", "СПА"),
                            ("pool", "Бассейн"),
                            ("conference", "Конференц-зал"),
                            ("territory", "Территория"),
                            ("other", "Другое"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="раздел",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активно"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="на главной"
                    ),
                ),
            ],
            options={
                "verbose_name": "фото галереи",
                "verbose_name_plural": "галерея гостиницы",
                "ordering": ["section", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Уникальный идентификатор блока, например: hero_title",
                        max_length=100,
                        unique=True,
                        verbose_name="ключ",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Понятное название для редактора",
                        max_length=200,
                        verbose_name="название",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("html", "HTML"),
                            ("image", "Изображение"),
                            ("url", "Ссылка"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="тип контента",
                    ),
                ),
                ("value_text", models.TextField(blank=True, verbose_name="текст")),
                (
                    "value_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/%Y/%m/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "контент сайта",
                "verbose_name_plural": "контент сайта",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Отображается на сайте",
                        max_length=100,
                        verbose_name="имя автора",
                    ),
                ),
                (
                    "author_title",
                    models.CharField(
                        blank=True,
                        help_text="Например: Москва или Директор компании",
                        max_length=100,
                        verbose_name="должность / город",
                    ),
                ),
                (
                    "author_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/%Y/",
                        verbose_name="фото автора",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст отзыва")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активен"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Например: Booking.com, TripAdvisor, личный визит",
                        max_length=100,
                        verbose_name="источник",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если оставлен реальным гостем системы",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы (главная)",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
