# Generated by Kilo

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=20, choices=[('terms', 'Условия использования'), ('privacy', 'Политика конфиденциальности'), ('accommodation', 'Политика проживания')], unique=True, verbose_name='тип страницы')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(help_text='Поддерживается HTML', verbose_name='содержание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'правовая страница',
                'verbose_name_plural': 'правовые страницы',
                'ordering': ['page_type'],
            },
        ),
    ]
