# Generated by Kilo

from django.db import migrations


def create_legal_pages(apps, schema_editor):
    LegalPage = apps.get_model("content", "LegalPage")
    defaults = [
        {
            "page_type": "terms",
            "title": "Условия использования",
            "content": "<p>Здесь будут условия использования сервиса.</p>",
            "is_active": True,
        },
        {
            "page_type": "privacy",
            "title": "Политика конфиденциальности",
            "content": "<p>Здесь будет политика конфиденциальности.</p>",
            "is_active": True,
        },
        {
            "page_type": "accommodation",
            "title": "Политика проживания",
            "content": "<p>Здесь будет политика проживания в гостинице.</p>",
            "is_active": True,
        },
    ]
    for data in defaults:
        LegalPage.objects.get_or_create(page_type=data["page_type"], defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_legalpage"),
    ]

    operations = [migrations.RunPython(create_legal_pages)]
