# Generated by Django 5.2.8 on 2026-05-21 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_aboutpage_stat2_bez_zvezd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_gallery_photo',
            field=models.ForeignKey(blank=True, help_text='Выберите фото из галереи гостиницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_blocks_about', to='content.hotelgallery', verbose_name='фото из галереи (блок О нас)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contacts_gallery_photo',
            field=models.ForeignKey(blank=True, help_text='Выберите фото из галереи гостиницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_blocks_contacts', to='content.hotelgallery', verbose_name='фото из галереи (блок Контакты)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='rooms_gallery_photo',
            field=models.ForeignKey(blank=True, help_text='Выберите фото из галереи гостиницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_blocks_rooms', to='content.hotelgallery', verbose_name='фото из галереи (блок Номера)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_gallery_photo',
            field=models.ForeignKey(blank=True, help_text='Выберите фото из галереи гостиницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_blocks_services', to='content.hotelgallery', verbose_name='фото из галереи (блок Сервис)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Альтернатива: загрузить файл, если не выбрано фото из галереи', null=True, upload_to='about/%Y/%m/', verbose_name='фото для блока О нас (загрузка)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='contacts_image',
            field=models.ImageField(blank=True, help_text='Альтернатива: загрузить файл', null=True, upload_to='about/%Y/%m/', verbose_name='фото для блока Контакты (загрузка)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='rooms_image',
            field=models.ImageField(blank=True, help_text='Альтернатива: загрузить файл', null=True, upload_to='about/%Y/%m/', verbose_name='фото для блока Номера (загрузка)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='services_image',
            field=models.ImageField(blank=True, help_text='Альтернатива: загрузить файл', null=True, upload_to='about/%Y/%m/', verbose_name='фото для блока Сервис (загрузка)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat2_number',
            field=models.CharField(default='Без звезд', max_length=20, verbose_name='статистика 2: число'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat4_number',
            field=models.CharField(default='20+', max_length=20, verbose_name='статистика 4: число'),
        ),
    ]
