# Generated by Django 5.2.8 on 2026-05-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_strip_about_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='section',
            field=models.CharField(choices=[('exterior', 'Экстерьер'), ('lobby', 'Лобби'), ('restaurant', 'Ресторан'), ('spa', 'СПА'), ('pool', 'Бассейн'), ('conference', 'Конференц-зал'), ('territory', 'Территория'), ('about', 'О нас'), ('other', 'Другое')], db_index=True, default='other', max_length=20, verbose_name='раздел'),
        ),
    ]
