# Generated by Django 5.0.4 on 2026-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_add_occupancy_type_and_infants"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="early_check_in",
            field=models.BooleanField(
                default=False,
                help_text="Заезд до 12:00 — добавляется стоимость одних суток",
                verbose_name="ранний заезд (до 12:00)",
            ),
        ),
    ]
