# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("hotel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "Физическое лицо"),
                            ("organization", "Организация"),
                        ],
                        db_index=True,
                        default="individual",
                        max_length=20,
                        verbose_name="тип клиента",
                    ),
                ),
                (
                    "guest_type",
                    models.CharField(
                        choices=[
                            ("leisure", "Отдых"),
                            ("business", "Бизнес"),
                            ("corporate", "Корпоративный"),
                            ("vip", "VIP"),
                        ],
                        db_index=True,
                        default="leisure",
                        max_length=20,
                        verbose_name="тип гостя",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("vip", "VIP"),
                            ("inactive", "Неактивный"),
                            ("blacklisted", "Чёрный список"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="статус клиента",
                    ),
                ),
                (
                    "loyalty_tier",
                    models.CharField(
                        choices=[
                            ("standard", "Стандарт"),
                            ("silver", "Серебро"),
                            ("gold", "Золото"),
                            ("platinum", "Платина"),
                        ],
                        db_index=True,
                        default="standard",
                        max_length=20,
                        verbose_name="уровень лояльности",
                    ),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="баллы лояльности"
                    ),
                ),
                (
                    "total_stays",
                    models.PositiveIntegerField(
                        default=0, verbose_name="всего заездов"
                    ),
                ),
                (
                    "total_nights",
                    models.PositiveIntegerField(default=0, verbose_name="всего ночей"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="всего потрачено",
                    ),
                ),
                (
                    "first_stay_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="первый заезд"
                    ),
                ),
                (
                    "last_stay_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="последний заезд"
                    ),
                ),
                (
                    "preferred_floor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="предпочитаемый этаж"
                    ),
                ),
                (
                    "dietary_requirements",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="диетические требования",
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="особые потребности"),
                ),
                ("vip_notes", models.TextField(blank=True, verbose_name="VIP заметки")),
                (
                    "is_blacklisted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="в чёрном списке"
                    ),
                ),
                (
                    "blacklist_reason",
                    models.TextField(blank=True, verbose_name="причина блокировки"),
                ),
                (
                    "assigned_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="менеджер",
                    ),
                ),
                (
                    "preferred_room_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_by",
                        to="hotel.roomcategory",
                        verbose_name="предпочитаемая категория",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользоваостиница",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль клиента",
                "verbose_name_plural": "профили клиентов",
                "ordering": ["-total_spent"],
            },
        ),
        migrations.CreateModel(
            name="AdminComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("body", models.TextField(verbose_name="комментарий")),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Закреплённые комментарии показываются первыми",
                        verbose_name="закреплён",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_comments",
                        to="crm.clientprofile",
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий администратора",
                "verbose_name_plural": "комментарии администраторов",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Звонок"),
                            ("email", "Email"),
                            ("in_person", "Личная встреча"),
                            ("chat", "Чат"),
                            ("note", "Заметка"),
                            ("complaint", "Жалоба"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="тема")),
                ("body", models.TextField(verbose_name="содержание")),
                (
                    "outcome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="результат"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="решено"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата повторного контакта"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.clientprofile",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "взаимодействие",
                "verbose_name_plural": "взаимодействия",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="краткое название"
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("company", "Компания"),
                            ("government", "Государственная организация"),
                            ("ngo", "НКО"),
                            ("individual", "ИП"),
                        ],
                        db_index=True,
                        default="company",
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, verbose_name="ИНН"
                    ),
                ),
                ("kpp", models.CharField(blank=True, max_length=9, verbose_name="КПП")),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                (
                    "legal_address",
                    models.TextField(blank=True, verbose_name="юридический адрес"),
                ),
                (
                    "actual_address",
                    models.TextField(blank=True, verbose_name="фактический адрес"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="сайт")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="контактное лицо"
                    ),
                ),
                (
                    "corporate_discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="корпоративная скидка (%)",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="кредитный лимит",
                    ),
                ),
                (
                    "payment_terms_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="отсрочка платежа (дней)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активна"
                    ),
                ),
                (
                    "assigned_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="crm.organization",
                verbose_name="организация",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "Запрос"),
                            ("complaint", "Жалоба"),
                            ("request", "Просьба"),
                            ("feedback", "Отзыв"),
                            ("internal", "Внутреннее"),
                        ],
                        db_index=True,
                        default="inquiry",
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="тема")),
                ("body", models.TextField(verbose_name="текст")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messages/attachments/%Y/%m/",
                        verbose_name="вложение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Не прочитано"),
                            ("read", "Прочитано"),
                            ("replied", "Отвечено"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="прочитано в"
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="срочное"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="crm.clientprofile",
                        verbose_name="профиль клиента",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="crm.message",
                        verbose_name="ответ на",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получаостиница",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отправиостиница",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="crm_message_recipie_975be0_idx",
                    ),
                    models.Index(
                        fields=["booking", "created_at"],
                        name="crm_message_booking_f700bd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыта"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="срок"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="выполнена в"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="исполниостиница",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="crm.clientprofile",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
                "ordering": ["-priority", "due_date"],
                "indexes": [
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="crm_task_assigne_1d8686_idx",
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="crm_task_due_dat_2a3684_idx",
                    ),
                ],
            },
        ),
    ]
