# Generated by Django 5.0.4 on 2026-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="infants",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="грудничков (до 1 года)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="occupancy_type",
            field=models.CharField(
                choices=[
                    ("solo", "Один гость"),
                    ("newlyweds", "Молодожёны (одна кровать, +50%)"),
                    ("friends", "Друзья (две кровати, ×2)"),
                    ("two_guests", "Двое гостей (×2)"),
                ],
                db_index=True,
                default="solo",
                max_length=20,
                verbose_name="тип размещения",
            ),
        ),
    ]
