# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("confirmed", "Подтверждена"),
                            ("checked_in", "Заселён"),
                            ("checked_out", "Выселился"),
                            ("cancelled", "Отменена"),
                            ("no_show", "Незаезд"),
                            ("payment", "Оплата"),
                            ("note_added", "Заметка"),
                            ("modified", "Изменена"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="действие",
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("checked_in", "Заселён"),
                            ("checked_out", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("no_show", "Незаезд"),
                        ],
                        max_length=20,
                        verbose_name="статус после",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="заметка")),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="снимок данных"
                    ),
                ),
            ],
            options={
                "verbose_name": "история брони",
                "verbose_name_plural": "история броней",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="сумма",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("card", "Банковская карта"),
                            ("transfer", "Банковский перевод"),
                            ("online", "Онлайн-оплата"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("charge", "Оплата"), ("refund", "Возврат")],
                        default="charge",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="ID транзакции",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="подтверждён"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="подтверждён в"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
            ],
            options={
                "verbose_name": "платёж",
                "verbose_name_plural": "платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="номер брони",
                    ),
                ),
                (
                    "guest_first_name",
                    models.CharField(max_length=150, verbose_name="имя"),
                ),
                (
                    "guest_last_name",
                    models.CharField(max_length=150, verbose_name="фамилия"),
                ),
                (
                    "guest_patronymic",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="отчество"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона.",
                                regex="^\\+?[\\d\\s\\-\\(\\)]{7,20}$",
                            )
                        ],
                        verbose_name="телефон",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
                (
                    "check_in",
                    models.DateField(db_index=True, verbose_name="дата заезда"),
                ),
                (
                    "check_out",
                    models.DateField(db_index=True, verbose_name="дата выезда"),
                ),
                (
                    "adults",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="взрослых"
                    ),
                ),
                (
                    "children",
                    models.PositiveSmallIntegerField(default=0, verbose_name="детей"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="цена за ночь",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="итого",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="скидка",
                    ),
                ),
                (
                    "discount_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="причина скидки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("checked_in", "Заселён"),
                            ("checked_out", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("no_show", "Незаезд"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Не оплачено"),
                            ("partial", "Частично оплачено"),
                            ("paid", "Оплачено"),
                            ("refunded", "Возврат"),
                            ("failed", "Ошибка оплаты"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Сайт"),
                            ("phone", "Телефон"),
                            ("walk_in", "Стойка регистрации"),
                            ("ota", "OTA (Booking.com и др.)"),
                            ("corporate", "Корпоративный клиент"),
                        ],
                        db_index=True,
                        default="website",
                        max_length=20,
                        verbose_name="источник",
                    ),
                ),
                (
                    "auto_cancel_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Если бронь не подтверждена до этого времени — отменяется автоматически",
                        null=True,
                        verbose_name="автоотмена в",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="особые пожелания"),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="примерное время прибытия"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="примерное время отъезда"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="внутренние заметки"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отменено в"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="причина отмены"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="отменил",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если бронь создана сотрудником",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="создал",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="гость",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
