# Generated by Django 5.0.4 on 2026-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_infants_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создана'), ('confirmed', 'Подтверждена'), ('checked_in', 'Заселён'), ('checked_out', 'Выселился'), ('cancelled', 'Отменена'), ('no_show', 'Незаезд'), ('payment', 'Оплата'), ('note_added', 'Заметка'), ('modified', 'Изменена'), ('undo_check_in', 'Заселение отменено'), ('undo_check_out', 'Выселение отменено')], db_index=True, max_length=20, verbose_name='действие'),
        ),
    ]
