# Generated by Kilo

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookinghistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accommodation_policy_agreed',
            field=models.BooleanField(default=False, verbose_name='согласие с политикой проживания'),
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_policy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время согласия'),
        ),
    ]
