# Generated by Django 5.0.4 on 2026-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_accommodation_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="early_check_in",
            field=models.BooleanField(
                default=False,
                help_text="Заезд до 12:00 считается ранним и будет взиматься доплата 50% от стоимости одних суток",
                verbose_name="ранний заезд (до 12:00)",
            ),
        ),
    ]
