# Generated by Django 5.0.4 on 2026-05-22 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_alter_booking_early_check_in"),
        ("crm", "0002_add_organization_approval"),
        ("hotel", "0005_alter_roomreview_booking_alter_roomreview_guest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_at_least_one_adult",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("adults__gte", 1), ("children__gte", 1), _connector="OR"
                ),
                name="booking_at_least_one_guest",
            ),
        ),
    ]
