# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("bookings", "0001_initial"),
        ("hotel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingfunnel",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funnel_events",
                to="bookings.booking",
                verbose_name="бронирование",
            ),
        ),
        migrations.AddField(
            model_name="bookingfunnel",
            name="room_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funnel_events",
                to="hotel.roomcategory",
                verbose_name="категория номера",
            ),
        ),
        migrations.AddField(
            model_name="bookingfunnel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funnel_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользоваостиница",
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="room_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_views",
                to="hotel.roomcategory",
                verbose_name="категория номера",
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользоваостиница",
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuesnapshot",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_revenue_snapshot_per_month"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type", "viewed_at"], name="analytics_p_page_ty_1abf78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_key", "viewed_at"],
                name="analytics_p_session_f465aa_idx",
            ),
        ),
    ]
