# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("crm", "0001_initial"),
        ("hotel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Для корпоративных броней",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="crm.organization",
                verbose_name="организация",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Назначается при заселении",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="hotel.room",
                verbose_name="номер",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="hotel.roomcategory",
                verbose_name="категория номера",
            ),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="bookings.booking",
                verbose_name="бронирование",
            ),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_history_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кто изменил",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="bookings.booking",
                verbose_name="бронирование",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="принял оплату",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in", "check_out"], name="bookings_bo_check_i_3b9851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "check_in"], name="bookings_bo_status_8296ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["guest", "status"], name="bookings_bo_guest_i_261eaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["auto_cancel_at", "status"],
                name="bookings_bo_auto_ca_3cda95_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("check_out__gt", models.F("check_in"))),
                name="booking_checkout_after_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("adults__gte", 1)), name="booking_at_least_one_adult"
            ),
        ),
    ]
