# Generated by Django 5.0.4 on 2026-05-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_roomreview_booking_alter_roomreview_guest'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_status_70a1f9_idx',
            old_name='reviews_rev_status_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_author__8385c0_idx',
            old_name='reviews_rev_author_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_is_feat_191d4b_idx',
            old_name='reviews_rev_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_overall_a44160_idx',
            old_name='reviews_rev_rating_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='room_category',
            field=models.ForeignKey(blank=True, help_text='Категория номера, о которой вы оставляете отзыв', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews_for_category', to='hotel.roomcategory', verbose_name='категория номера'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='reviewmoderation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='author',
            field=models.ForeignKey(help_text='Сотрудник, написавший ответ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL, verbose_name='автор ответа'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
    ]
