# Generated by Django 5.0.4 on 2026-05-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_remove_booking_booking_at_least_one_adult_and_more"),
        (
            "reviews",
            "0002_rename_reviews_rev_status_idx_reviews_rev_status_70a1f9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                help_text="Если отзыв оставлен после проживания, он может быть привязан к конкретному бронированию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review",
                to="bookings.booking",
                verbose_name="бронирование",
            ),
        ),
    ]
