# Generated by Django 5.0.4 on 2026-05-22 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_remove_booking_booking_at_least_one_adult_and_more"),
        ("hotel", "0005_alter_roomreview_booking_alter_roomreview_guest"),
        ("reviews", "0003_alter_review_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("author",), name="unique_review_per_author"
            ),
        ),
    ]
