# Generated by Django 5.0.4 on 2026-05-07 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Бронь подтверждена"),
                    ("booking_cancelled", "Бронь отменена"),
                    ("checkin_reminder", "Напоминание о заезде"),
                    ("checkout_reminder", "Напоминание о выезде"),
                    ("loyalty_upgrade", "Повышение уровня лояльности"),
                    ("contact_form", "Обратная связь с сайта"),
                    ("system", "Системное"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="тип",
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("sender_name", models.CharField(max_length=150, verbose_name="имя")),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
                (
                    "sender_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="телефон"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="тема"),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_work", "В работе"),
                            ("answered", "Отвечено"),
                            ("closed", "Закрыто"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="назначено",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заполняется если гость авторизован",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение обратной связи",
                "verbose_name_plural": "сообщения обратной связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                ("body", models.TextField(verbose_name="текст")),
                (
                    "is_staff_reply",
                    models.BooleanField(default=False, verbose_name="ответ персонала"),
                ),
                (
                    "is_read_by_guest",
                    models.BooleanField(default=False, verbose_name="прочитано гостем"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notifications.contactmessage",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_5ffbd1_idx"
            ),
        ),
    ]
