# Generated by Django 5.0.4 on 2026-05-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookinghistory_action'),
        ('hotel', '0004_add_missing_fields_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_review_legacy', to='bookings.booking', verbose_name='бронирование'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reviews', to=settings.AUTH_USER_MODEL, verbose_name='гость'),
        ),
    ]
