# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="сессия"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("search", "Поиск"),
                            ("room_view", "Просмотр номера"),
                            ("form_open", "Открыл форму"),
                            ("form_submit", "Отправил форму"),
                            ("success", "Успешное бронирование"),
                            ("abandoned", "Брошено"),
                        ],
                        db_index=True,
                        default="search",
                        max_length=20,
                        verbose_name="этап",
                    ),
                ),
                (
                    "search_check_in",
                    models.DateField(blank=True, null=True, verbose_name="искал заезд"),
                ),
                (
                    "search_check_out",
                    models.DateField(blank=True, null=True, verbose_name="искал выезд"),
                ),
                (
                    "search_guests",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="гостей"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="начало"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
            ],
            options={
                "verbose_name": "воронка бронирования",
                "verbose_name_plural": "воронки бронирования",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="дата"),
                ),
                (
                    "total_rooms",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="всего номеров"
                    ),
                ),
                (
                    "occupied_rooms",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="занято номеров"
                    ),
                ),
                (
                    "available_rooms",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="свободно номеров"
                    ),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="загрузка (%)",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="выручка",
                    ),
                ),
                (
                    "adr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Average Daily Rate = выручка / занятые номера",
                        max_digits=10,
                        verbose_name="ADR (средняя цена)",
                    ),
                ),
                (
                    "revpar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Revenue Per Available Room = выручка / все номера",
                        max_digits=10,
                        verbose_name="RevPAR",
                    ),
                ),
                (
                    "new_bookings",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="новых броней"
                    ),
                ),
                (
                    "confirmed_bookings",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="подтверждено"
                    ),
                ),
                (
                    "cancelled_bookings",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="отменено"
                    ),
                ),
                (
                    "checkins",
                    models.PositiveSmallIntegerField(default=0, verbose_name="заездов"),
                ),
                (
                    "checkouts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="выездов"),
                ),
                (
                    "no_shows",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="не явились"
                    ),
                ),
                (
                    "total_guests",
                    models.PositiveSmallIntegerField(default=0, verbose_name="гостей"),
                ),
                (
                    "new_guests",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="новых гостей"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="рассчитано в"),
                ),
            ],
            options={
                "verbose_name": "метрики за день",
                "verbose_name_plural": "метрики по дням",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Главная"),
                            ("room_list", "Список номеров"),
                            ("room_detail", "Страница номера"),
                            ("booking_form", "Форма бронирования"),
                            ("booking_success", "Успешное бронирование"),
                            ("about", "О нас"),
                            ("contacts", "Контакты"),
                            ("other", "Другое"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="тип страницы",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="URL")),
                (
                    "referrer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="реферер"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, verbose_name="сессия"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="просмотрено"
                    ),
                ),
            ],
            options={
                "verbose_name": "просмотр страницы",
                "verbose_name_plural": "просмотры страниц",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(db_index=True, verbose_name="год"),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="месяц",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="выручка",
                    ),
                ),
                (
                    "total_bookings",
                    models.PositiveIntegerField(default=0, verbose_name="броней"),
                ),
                (
                    "total_nights",
                    models.PositiveIntegerField(default=0, verbose_name="ночей"),
                ),
                (
                    "avg_occupancy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="средняя загрузка (%)",
                    ),
                ),
                (
                    "avg_adr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="средний ADR",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="рассчитано"),
                ),
            ],
            options={
                "verbose_name": "снимок выручки",
                "verbose_name_plural": "снимки выручки",
                "ordering": ["-year", "-month"],
            },
        ),
    ]
