# Generated by Django 5.0.4 on 2026-04-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Подтверждение брони"),
                            ("booking_cancelled", "Отмена брони"),
                            ("booking_reminder", "Напоминание о заезде"),
                            ("booking_checkout", "Благодарность за визит"),
                            ("password_reset", "Сброс пароля"),
                            ("welcome", "Приветствие"),
                            ("marketing", "Маркетинговая рассылка"),
                            ("custom", "Произвольное"),
                        ],
                        help_text="Один шаблон на каждый тип письма",
                        max_length=30,
                        unique=True,
                        verbose_name="тип письма",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "subject",
                    models.CharField(
                        help_text="Доступные переменные: {{ booking.confirmation_number }}, {{ guest.first_name }}, …",
                        max_length=500,
                        verbose_name="тема письма",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="Django template. Наследуется от notifications/email/base_email.html",
                        verbose_name="HTML шаблон",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Автоматически генерируется из HTML если не заполнен",
                        verbose_name="текстовый шаблон",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "шаблон письма",
                "verbose_name_plural": "шаблоны писем",
                "ordering": ["email_type"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="получаостиница"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="имя получаостиницы"
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Подтверждение брони"),
                            ("booking_cancelled", "Отмена брони"),
                            ("booking_reminder", "Напоминание о заезде"),
                            ("booking_checkout", "Благодарность за визит"),
                            ("password_reset", "Сброс пароля"),
                            ("welcome", "Приветствие"),
                            ("marketing", "Маркетинговая рассылка"),
                            ("custom", "Произвольное"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=30,
                        verbose_name="тип письма",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="тема")),
                ("body_html", models.TextField(blank=True, verbose_name="HTML тело")),
                (
                    "body_text",
                    models.TextField(blank=True, verbose_name="текстовое тело"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("bounced", "Отклонено сервером"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отправлено в"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="ошибка")),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="попыток"),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Celery task ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользоваостиница",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог email",
                "verbose_name_plural": "лог email",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_6192b4_idx",
                    ),
                    models.Index(
                        fields=["email_type", "created_at"],
                        name="notificatio_email_t_80ca13_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "email_type"],
                        name="notificatio_recipie_0cb1ea_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Бронь подтверждена"),
                            ("booking_cancelled", "Бронь отменена"),
                            ("checkin_reminder", "Напоминание о заезде"),
                            ("checkout_reminder", "Напоминание о выезде"),
                            ("loyalty_upgrade", "Повышение уровня лояльности"),
                            ("system", "Системное"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="тип",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("body", models.TextField(verbose_name="текст")),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL для кнопки 'Подробнее'",
                        max_length=500,
                        verbose_name="ссылка",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="прочитано"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="прочитано в"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_notifications",
                        to="bookings.booking",
                        verbose_name="бронирование",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получаостиница",
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_caf16f_idx",
                    )
                ],
            },
        ),
    ]
